- name: start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
    
- name: firewalld open port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: firewalld open port 443
  firewalld:
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled

