- name: start firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
    
- name: firewalld open ports
  firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 443/tcp
    - 80/tcp
    - 8080/tcp
