---
- name: preconfigure | use python3
  hosts: all
  become: true

  roles:
    - preconfigure
  tags: preconf 

- name: install and configure db servers
  hosts: db
  become: true

  roles:
    - db
  tags: db

- name: install and configure app servers
  hosts: app
  become: true

  roles:
    - app
  tags: app

- name: install and configure load balancers
  hosts: lb
  become: true

  roles:
    - lb
  tags: lb

- name: install and configure backup server
  hosts: backup
  become: true

  roles:
    - backup
  tags: backup

- name: install and configure log servers
  hosts: log
  become: true

  roles:
    - log
  tags: log