---
# handlers file for roles/lb

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes