
- name: start glusterfs service
  systemd:
    name: glusterd
    state: started
    enabled: yes

- name: ensure gluster brick and mount directories exist.
  file: 
    path: '{{ item }}'
    state: directory 
    mode: 0775
  loop:
    - '{{ gluster_brick_dir }}'
    - '{{ app_directory }}'

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    replicas: 3
    cluster: "{{ groups.app | join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ app_directory }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
