
- name: download and extract wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: add user wordpress 
  proxysql_mysql_users:
    login_user: 'admin'
    login_password: 'admin'
    username: '{{ wordpress_user }}'
    password: '{{ wordpress_password }}'
    state: present

- name: copy wp-config
  copy:
    src: wp-config.php
    dest: /var/www/html/wordpress
