
- name: add user monitor
  mysql_user:
    name: '{{ monitor_user }}'
    password: '{{ monitor_password }}'
    host: '%'
    priv: '*.*:ALL'
    state: present
  when: 
    - cluster_node_state  == "master"