- name: start proxysql
  systemd:
    name: proxysql
    state: started
    enabled: yes

- name: copy password to ~/.my.cnf
  copy:
    content: |
        [client]
        user=admin
        password='admin'
        host=127.0.0.1
        port=6032
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0644

- name: add cluster node
  shell: |
    mysql << EOF
      INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0, 'db1', 3306);
      INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0, 'db2', 3306);
      INSERT INTO mysql_servers(hostgroup_id, hostname, port) VALUES (0, 'db3', 3306);
      LOAD MYSQL SERVERS TO RUNTIME;
      SAVE MYSQL SERVERS TO DISK;
    EOF
